[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
wannabet_escrow = "H1fMNM3LC2Ljy6auyBVzeTvE2aeG4CTDRhpm6crn5bVW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
