[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
wannabet_escrow = "Dp2U48v9tF2PwUVeg92tGSwxgC2r85XddpB7Ts5BBcPH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
